/**
 * Photography portfolio data. Image paths are relative to the site root
 * (place files under public/photos/... so Vite serves them at /photos/...).
 */

export const CAROUSEL_PHOTOS = [
  // { src: "/photos/featured/shot1.jpg", caption: "Downtown LA, 5:42am" },
];

export const SERIES = [
  {
    id: "urban-solitude",
    title: "Urban Solitude",
    titleItalic: "Solitude",
    tag: "Street · Documentary",
    meta: "Los Angeles · 2023",
    desc: "A study of stillness within chaos — early morning streets, long shadows, and the quiet architecture of a city before it wakes. Shot over six weeks on Kodak Portra 400.",
    tags: ["35mm", "Portra 400", "Street", "Golden hour"],
    camera: "Nikon FM2",
    film: "Portra 400",
    duration: "6 weeks",
    shots: "24 images",
    folder: "/photos/urban-solitude/",
    images: [],
  },
  {
    id: "pacific-coast",
    title: "Pacific Coast Dusk",
    titleItalic: "Dusk",
    tag: "Landscape · Natural",
    meta: "California · 2024",
    desc: "Golden hour along the Pacific coastline. Long exposures, wide skies, and the last light of the day.",
    tags: ["Digital", "Golden hour", "Landscape"],
    camera: "Sony A7III",
    film: "Digital",
    duration: "3 months",
    shots: "18 images",
    folder: "/photos/pacific-coast/",
    images: [],
  },
  {
    id: "quiet-faces",
    title: "Quiet Faces",
    titleItalic: "Faces",
    tag: "Portrait · Fine-art",
    meta: "Studio · 2024",
    desc: "Candid and directed portraits — stillness, expression, and available light.",
    tags: ["Studio", "Portrait", "Film"],
    camera: "Nikon FM2",
    film: "Ilford HP5",
    duration: "Ongoing",
    shots: "30 images",
    folder: "/photos/quiet-faces/",
    images: [],
  },
  {
    id: "grid-lines",
    title: "Grid Lines",
    titleItalic: "Lines",
    tag: "Architecture · Urban",
    meta: "Downtown LA · 2023",
    desc: "The geometry of the built environment — repeating patterns, shadows on concrete, the city as abstract form.",
    tags: ["Architecture", "Urban", "35mm"],
    camera: "Nikon FM2",
    film: "Kodak T-Max",
    duration: "4 weeks",
    shots: "20 images",
    folder: "/photos/grid-lines/",
    images: [],
  },
  {
    id: "desert-intervals",
    title: "Desert Intervals",
    titleItalic: "Intervals",
    tag: "Landscape · Golden hour",
    meta: "Joshua Tree · 2023",
    desc: "Vast space, long light, and the silence of the high desert at dusk.",
    tags: ["Desert", "Landscape", "Golden hour", "35mm"],
    camera: "Nikon FM2",
    film: "Portra 400",
    duration: "2 weekends",
    shots: "22 images",
    folder: "/photos/desert-intervals/",
    images: [],
  },
  {
    id: "film-experiments",
    title: "Film Experiments",
    titleItalic: "Experiments",
    tag: "Abstract · Experimental",
    meta: "35mm analogue · 2024",
    desc: "Cross-processing, expired film, light leaks and happy accidents.",
    tags: ["Experimental", "35mm", "Analogue"],
    camera: "Various",
    film: "Mixed",
    duration: "Ongoing",
    shots: "40 images",
    folder: "/photos/film-experiments/",
    images: [],
  },
];

export const GRAD_PHOTOS = {
  folder: "/photos/grad/",
  images: [],
};
